#!/usr/bin/env bash

export NVM_DIR=/usr/local/nvm

source $NVM_DIR/nvm.sh

export NODE_PATH=$NVM_DIR/v$NODE_VERSION/lib/node_modules
export PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

if [ -d "/autograder/" ]; then
	export NODE_ENV=prod
	SOURCE_DIR=/autograder/source

    echo "[GS] Running on Gradescope container, using Gradescope config"
else
	export NODE_ENV=dev
	SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

    echo "[GS] Running on dev env, using local config"
fi

# run the node script
cd $SOURCE_DIR

node .
